routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Home Utama User
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home', 'HomeController@store');

//create comment
Route::post('/home/comment/{id}','CommentController@store')->name('post.comment');
Route::delete('/home/comment/{id}', 'CommentController@destroy');
Route::get('/home/comment/{id}', 'CommentController@show');

//Profile User CRUD
Route::resource('profile', 'ProfileController');
//post crud
Route::resource('post', 'PostController');

resources/views/comment.blade.php
@extends('layouts.app')
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
  <div class="container">
          <a class="navbar-brand" href="{{ url('/') }}">
              {{ config('app.name', 'Laravel') }}</a>
      <td><a href="/home">Home</a></td>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">

          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
              <!-- Authentication Links -->
              @guest
                  <li class="nav-item">
                      <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                  </li>
                  @if (Route::has('register'))
                      <li class="nav-item">
                          <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                      </li>
                  @endif
              @else
                  <li class="nav-item dropdown">
                      <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                          {{ Auth::user()->name }} <span class="caret"></span>
                      </a>

                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{ route('logout') }}"
                             onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                              {{ __('Logout') }}
                          </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>
                      </div>
                  </li>
              @endguest
          </ul>
      </div>
  </div>
</nav>
@section('content')
<div class="row justify-content-center">
    <div class="card mb-4 mt-4 col-md-8">
        <div class="card-body">
            {{-- //tulisan pada tampilan postingan --}}
            <p class="card-text">{{$show->user->name}}</p>
            <p class="card-text">{{$show-> isi}}</p>
        </div>
        <div class="card-footer text-muted col-md-12">
          Tags:
          @forelse ($show->tags as $tag)
          <button class="btn btn-primary btn-sm">{{ $tag->tag_name }}</button> 
          @empty
          No tags       
          @endforelse
          <br>
          <br>
          <form action="/home/comment/{{$show->id}}" method="POST">
            @csrf
            <input type="text" class="isi col-9" id="isi" name="isi" placeholder="Add Comment">
            <br>
            <button type="submit" class="btn btn-primary btn-sm mt-2">Add Comment</button>
          </form>     
          </div>
          @forelse ($posts as $item => $data)
          <div class="card mb-2 mt-8 col-md-12">
           <div class="card-body">
              <p class="card-text">{{$data->isi}}</p>
              <form action="/home/comment/{{$data->id}}" method="POST">
                @csrf
                @method('DELETE')
                <input type="submit" value="delete" class="btn btn-danger mt-2 btn-sm">
            </form>
            </div>
          </div>
          @empty
              
          @endforelse
      </div>
</div>
</div>
@endsection
@if(session('success'))
@push('scripts')
<script>
  Swal.fire({
    title: 'Berhasil!',
    text:  'Comment Berhasil Dibuat',
    icon:  'success',
    confirmButtonText: 'Cool'
  })
</script>
 @endpush
 {{ session('success')}}
 @endif

resources/views/createprofile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create New Profile') }}</div>

                <div class="card-body">
                    <form method="POST" action="/profile" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                            <label for="nama" class="col-md-4 col-form-label text-md-right">{{ __('Nama') }}</label>
                            <div class="col-md-6">
                                <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="alamat" class="col-md-4 col-form-label text-md-right">{{ __('Alamat') }}</label>
                            <div class="col-md-6">
                                <input id="alamat" type="text" class="form-control @error('alamat') is-invalid @enderror" name="alamat" value="{{ old('alamat') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="ttl" class="col-md-4 col-form-label text-md-right">{{ __('Tanggal Lahir') }}</label>
                            <div class="col-md-6">
                                <input id="ttl" type="date" class="form-control @error('ttl') is-invalid @enderror" name="ttl" value="{{ old('ttl') }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>
                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="photo" class="col-md-4 col-form-label text-md-right">{{ __('Photo') }}</label>
                            <input type="file" name="photo" id="photo">
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create Profile') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Profile') }}</div>

                <div class="card-body">
                    <form method="POST" action="/profile/{{Auth::id()}}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="nama" class="col-md-4 col-form-label text-md-right">{{ __('Nama') }}</label>
                            <div class="col-md-6"> 
                                <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{!empty(Auth::user()->profile->nama) ? Auth::user()->profile->nama:"" }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="alamat" class="col-md-4 col-form-label text-md-right">{{ __('Alamat') }}</label>
                            <div class="col-md-6">
                                <input id="alamat" type="text" class="form-control @error('alamat') is-invalid @enderror" name="alamat" value="{{!empty(Auth::user()->profile->alamat) ? Auth::user()->profile->alamat:"" }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="ttl" class="col-md-4 col-form-label text-md-right">{{ __('Tanggal Lahir') }}</label>
                            <div class="col-md-6">
                                <input id="ttl" type="date" class="form-control @error('ttl') is-invalid @enderror" name="ttl" value="{{!empty(Auth::user()->profile->ttl) ? Auth::user()->profile->ttl:"" }}">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>
                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{!empty(Auth::user()->profile->email) ? Auth::user()->profile->email:"" }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="photo" class="col-md-4 col-form-label text-md-right">{{ __('Photo') }}</label>
                            <input type="file" name="photo" id="photo">
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update Profile') }}
                                </button>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/editpost.blade.php
@extends('layouts.app')
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}</a>
        <td><a href="/profile">Profile</a></td>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
  
            </ul>
  
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>
  
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
  
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
  </nav>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                Hello, {{Auth::user()->name}}
                </div>
                <form action="{{route('post.update', ['post'=>$post->id ])}}" method="POST">
                    @csrf
                    @method('PUT')
                      <div class="card-body">
                        <div class="form-group">
                          <textarea class="form-control" name="isi" id="isi" 
                          value="{{ old('isi','') }}" placeholder="What's New?" 
                          cols="15" rows="5"></textarea>
                          <label for="tags" class="mt-2">Tags</label>
                          <input type="text" class="tags col-12" id="tags" name="tags" placeholder="Pisahkan dengan koma. Contoh: Baru, Lama">
                        </div>
                          @error('isi')
                          <div class="alert alert-danger">{{ $message }}</div>
                          @enderror
                      </div>
                      <!-- /.card-body -->
      
                      <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Edit Post</button>
                      </div>
                    </form>
            </div>
        </div>
    </div>

resources/views/home.blade.php
@extends('layouts.app')

<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
  <div class="container">
          <a class="navbar-brand" href="{{ url('/') }}">
              {{ config('app.name', 'Laravel') }}</a>
      <td><a href="/profile">Profile</a></td>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">

          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
              <!-- Authentication Links -->
              @guest
                  <li class="nav-item">
                      <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                  </li>
                  @if (Route::has('register'))
                      <li class="nav-item">
                          <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                      </li>
                  @endif
              @else
                  <li class="nav-item dropdown">
                      <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                          {{ Auth::user()->name }} <span class="caret"></span>
                      </a>

                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{{ route('logout') }}"
                             onclick="event.preventDefault();
                                           document.getElementById('logout-form').submit();">
                              {{ __('Logout') }}
                          </a>

                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                              @csrf
                          </form>
                      </div>
                  </li>
              @endguest
          </ul>
      </div>
  </div>
</nav>

@section('content')
{{-- Membuat Header Postingan --}}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                Hello, {{Auth::user()->name}}
                </div>
                <form role="form" action="/home" method="POST">
                    @csrf
                      <div class="card-body">
                        <div class="form-group">
                          <textarea class="form-control" name="isi" id="isi" 
                          value="{{ old('isi','') }}" placeholder="What's New?" 
                          cols="15" rows="5"></textarea>
                          <label for="tags" class="mt-2">Tags</label>
                          <input type="text" class="tags col-12" id="tags" name="tags" placeholder="Pisahkan dengan koma. Contoh: Baru, Lama">
                        </div>
                          @error('isi')
                          <div class="alert alert-danger">{{ $message }}</div>
                          @enderror
                      </div>
                      <!-- /.card-body -->
      
                      <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Post</button>
                      </div>
                    </form>
            </div>
        </div>
    </div>

    {{-- Membuat Postingan user --}}
    
    <div class="row justify-content-center">
        @forelse($show as $key => $post)
        <div class="card mb-4 mt-4 col-md-8">
            <div class="card-body">
                {{-- //tulisan pada tampilan postingan --}}
               <p class="card-text">{{$post->user->name}}</p>
                <p class="card-text">{{$post->isi}}</p>
            </div>
            <div class="card-footer text-muted col-md-12">
              Tags:
              @forelse ($post->tags as $tag)
              <button class="btn btn-primary btn-sm">{{ $tag->tag_name }}</button> 
              @empty
              No tags       
              @endforelse
              <br><br>
              <a href="/home/comment/{{$post->id}}" type="submit" class="btn btn-primary btn-sm">Add Comment</a>
              </div>
          </div>
         
          @empty
          <tr>
            <td colspan="4" align="center">No Data</td>
          </tr>

    @endforelse
    </div>
    </div>
   
@endsection
@if(session('success'))
@push('scripts')
<script>
  Swal.fire({
    title: 'Berhasil!',
    text:  'Post Berhasil Dibuat',
    icon:  'success',
    confirmButtonText: 'Cool'
  })
</script>
 @endpush
 {{ session('success')}}
 @endif

resources/views/profile.blade.php
@extends('layouts.app')
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}</a>
        <td><a href="/home">Home</a></td>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
@section('content')
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<img src={{url('/img/'.$check->photo)}} class="img-responsive" alt="{{url('/img/noimage.jpg')}}">
				</div>
				<!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                        @empty (Auth::user()->profile->nama)
                        <div class="row justify-content-center"><a href="/profile/create" class="btn btn-primary btn-sm">Create New Profile</a></div>
                        @endempty
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						{{!empty(Auth::user()->profile->nama) ? Auth::user()->profile->nama:"Your Name" }}
                    </div>
					<div class="profile-usertitle-job">
						{{!empty(Auth::user()->profile->ttl) ? Auth::user()->profile->ttl:"Date of Birth"}}
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">Follow</button>
					<button type="button" class="btn btn-danger btn-sm">Message</button>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							{{!empty(Auth::user()->profile->alamat) ? Auth::user()->profile->alamat:"City"}} </a>
						</li>
						
						<li>
							<a href="#" target="_blank">
							<i class="glyphicon glyphicon-ok"></i>
							{{!empty(Auth::user()->profile->email) ? Auth::user()->profile->email:"Email"}} </a>
						</li>
						
                        <li>
							<a href="/profile/{{Auth::id()}}/edit">
							<i class="glyphicon glyphicon-user"></i>
							Edit/Create Profile</a>
						</li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
            <div class="profile-content">
                <div class="row justify-content-center">
                    @forelse($posts as $key => $post)
                    <div class="card mb-4 mt-4 col-md-8">
                        <div class="card-body">
                            {{-- //tulisan pada tampilan postingan --}}
                            <p class="card-text">{{Auth::user()->name}}</p>
                            <p class="card-text">{{$post->isi}}</p>
                            <tr>
                                <td><a href="#" class="btn btn-default btn-sm">Edit Post</a></li>
                                <td>
                                    <form action="/profile/{{$post->id}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" value="delete" class="btn btn-danger mt-2 btn-sm">
                                    </form>
                                </td>
                            </tr>
                 
                        </div>
                        <div class="card-footer text-muted">
                            Tags:
                            @forelse ($post->tags as $tag)
                            <button class="btn btn-primary btn-sm">{{ $tag->tag_name }}</button> 
                            @empty
                            No tags       
                            @endforelse                            
                        </div>
                        </div>
                      </div>
                      @empty
                      <tr>
                        <td colspan="4" align="center">No Data</td>
                      </tr>
                @endforelse
                </div>
            </div>
		</div>
	</div>
</div>
@endsection

resources/views/upload.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Tutorial Laravel #30 : Membuat Upload File Dengan Laravel</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
	<div class="row">
		<div class="container">

			<h2 class="text-center my-5">Tutorial Laravel #30 : Membuat Upload File Dengan Laravel</h2>
			
			<div class="col-lg-8 mx-auto my-5">	

				@if(count($errors) > 0)
				<div class="alert alert-danger">
					@foreach ($errors->all() as $error)
					{{ $error }} <br/>
					@endforeach
				</div>
				@endif

				<form action="/upload/proses" method="POST" enctype="multipart/form-data">
					{{ csrf_field() }}

					<div class="form-group">
						<b>File Gambar</b><br/>
						<input type="file" name="file">
					</div>

					<div class="form-group">
						<b>Keterangan</b>
						<textarea class="form-control" name="keterangan"></textarea>
					</div>

					<input type="submit" value="Upload" class="btn btn-primary">
				</form>
				
				<h4 class="my-5">Data</h4>

				<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<th width="1%">File</th>
							<th>Keterangan</th>
							<th width="1%">OPSI</th>
						</tr>
					</thead>
					<tbody>
						@foreach($gambar as $g)
						<tr>
							<td><img width="150px" src="{{ url('/data_file/'.$g->file) }}"></td>
							<td>{{$g->keterangan}}</td>
							<td><a class="btn btn-danger" href="/upload/hapus/{{ $g->id }}">HAPUS</a></td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</body>
</html>